title: Palestine Is Everywhere 
description: Students throughout the United States have set up encampments on their campuses in solidarity with the Palestinian people. They are protesting their universities"'" investments and complicity in the ongoing genocide, occupation, and ethnic cleansing of the Palestinian people. This map captures the emergence of widespread support for the Palestinian resistance as more colleges and universities rise up each day. The students will not stop until their demands are met. 
logo: FreePalestineActupLogo.jpg
theme: jekyll-theme-minimal
Read more about Palestine here.
